import type { Metadata } from "next";
import { Commissioner, Jost } from "next/font/google";
import "./globals.css";
import { Header } from "../components/site/header";
import { Footer } from "../components/site/Footer";

const commissioner = Commissioner({
  variable: "--font-commissioner",
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <Header />
      <body className="min-h-full flex flex-col">{children}</body>
      <Footer />
    </html>
  );
}
